#Creating my first github action yaml
name: First test
# Create Events for trigger
on: [push]

#create Jobs - Jobs are set of Steps.
jobs:
  build: #this is basically stage
   runs-on: ubuntu-latest #runner in which job will run
   steps:
    - uses: actions/checkout@v2 #this is checkut your repository in the runner
    - run: |
         git config --global user.name "Checkmate"
         git config --global user.email "saurabh.singh@aptech.ac.in"
         git log --oneline >> log_$(date +%T).txt
       
   
   

