#Creating my first github action yaml
name: First test
# Create Events for trigger
on: [push]

#create Jobs - Jobs are set of Steps.
jobs:
  build: #this is basically stage
   runs-on: ubuntu-latest #runner in which job will run
   steps:
    - uses: actions/checkout@v2 #this is checkut your repository in the runner
    - uses: google-github-actions/setup-gcloud@master
    - run: echo "This is New Push" >> log_$(date +%T).txt
       
   
   

